repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest-targeted
        entry: python3 run_precommit_tests.py
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
